name: 😲Configure AWS CLI😲

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS CLI 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AccessKeyId }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AccessKeySecret }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1
          aws configure set default.output json
